server:
  port: 8080
  servlet:
    context-path: /decrypto-api

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: "jdbc:mysql://localhost:3306/decrypto-database"
    username: "root"
    password: "4aefeb42-2584-4c53-b89b-9ab6e4fc1776"
    hikari:
      maximum-pool-size: 10
    jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true